<?php
require_once __DIR__ . '/_auth.php';
require_once __DIR__ . '/../config/DatabaseConnection.php';
$db = new DatabaseConnection();
$connection = $db->openConnection();
$result = $db->getAllReviews($connection);
$summary = $connection->query("SELECT COALESCE(AVG(cleanliness_rating),0) cleanliness, COALESCE(AVG(service_rating),0) service, COALESCE(AVG(overall_rating),0) overall FROM reviews")->fetch_assoc();
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>ZELO - Guest Reviews</title><link rel="stylesheet" href="assets/css/review.css"><script src="assets/js/review.js" defer></script></head><body><div class="app"><?php include __DIR__ . '/_sidebar.php'; ?><main class="main"><div class="pageheader"><div><h2>Guest reviews</h2><span class="subtext">Average rating <?= number_format((float)$summary['overall'],1) ?>/ 5</span></div></div><div class="stats-row"><div class="stat-item"><div class="stat-score"><?= number_format((float)$summary['cleanliness'],1) ?></div><div class="stat-label">Cleanliness</div></div><div class="stat-item"><div class="stat-score"><?= number_format((float)$summary['service'],1) ?></div><div class="stat-label">Service</div></div><div class="stat-item"><div class="stat-score"><?= number_format((float)$summary['overall'],1) ?></div><div class="stat-label">Overall</div></div></div><div class="panel"><div class="panel-header"><h3>Recent reviews</h3></div><div class="reviews-list"><?php while($r=$result->fetch_assoc()): ?><div class="review-card"><div class="review-header"><span class="reviewer-name"><?= htmlspecialchars($r['guest_name']) ?></span><div class="stars"><?= number_format((float)$r['overall_rating'],1) ?>/5</div></div><p class="review-text">"<?= htmlspecialchars($r['review_text'] ?? '') ?>"</p><div class="review-meta">Room <?= htmlspecialchars($r['room_number'] ?? '-') ?> · <?= htmlspecialchars($r['room_type'] ?? '-') ?> · <?= date('M j', strtotime($r['created_at'])) ?></div><?php if(empty($r['admin_reply'])): ?><a href="#" class="reply-link">Post official reply →</a><?php else: ?><span class="replied-status">Replied ✓</span><?php endif; ?></div><?php endwhile; ?></div></div></main></div></body></html>
